# Generated by Django 3.0.4 on 2020-03-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Saisie Ouverte'), (2, 'Saisie Fermée'), (3, 'Bourse Ouverte'), (4, 'Bourse Fermée')], default=2, verbose_name='Event Status'),
        ),
    ]
