# Generated by Django 3.0.4 on 2020-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0002_auto_20200327_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold_date',
            field=models.DateTimeField(blank=True, verbose_name='Date Sold'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='list_status',
            field=models.IntegerField(choices=[(1, 'Editable'), (2, 'Validated'), (3, 'Archived')], default=1, verbose_name='List Status'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='validated_date',
            field=models.DateTimeField(blank=True, verbose_name='Date Validated'),
        ),
    ]
