# Generated by Django 3.0.4 on 2020-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0003_auto_20200329_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Sold'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='validated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Validated'),
        ),
    ]
