# Generated by Django 3.2.12 on 2022-03-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0004_auto_20200329_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='list_status',
            field=models.IntegerField(choices=[(1, 'Editable'), (2, 'Validated'), (3, 'Admin validated'), (4, 'Archived')], default=1, verbose_name='List Status'),
        ),
    ]
