# Generated by Django 3.2.12 on 2022-04-18 10:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0006_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comments',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
