# Generated by Django 3.2.12 on 2023-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0011_alter_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='copied_from',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Copied from'),
        ),
        migrations.AddField(
            model_name='item',
            name='copied_to',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Copied to'),
        ),
    ]
